[project]
name = "ecmsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2022.12.7",
    "charset-normalizer>=2.1.1",
    "grpcio>=1.83.0",
    "grpcio-tools>=1.83.0",
    "idna>=3.4",
    "logging>=0.4.9.6",
    "matplotlib>=3.11.1",
    "numpy>=2.4.4",
    "pyyaml>=6.0.3",
    "scipy>=1.18.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.28.0",
    "urllib3>=1.26.13",
]

[tool.uv.sources]
torch = { index = "pytorch-cu127" }
torchvision = { index = "pytorch-cu127" }
torchaudio = { index = "pytorch-cu127" }

[[tool.uv.index]]
name = "pytorch-cu127"
url = "https://download.pytorch.org/whl/cu126"
