# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.agent_service_pb2 as agent__service__pb2


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/ecmsim.AgentService/GetState',
                request_serializer=agent__service__pb2.StateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.StateResponse.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/ecmsim.AgentService/ExecuteAction',
                request_serializer=agent__service__pb2.ActionRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.StepSimulation = channel.unary_unary(
                '/ecmsim.AgentService/StepSimulation',
                request_serializer=agent__service__pb2.StepRequest.SerializeToString,
                response_deserializer=agent__service__pb2.StepResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=agent__service__pb2.StateRequest.FromString,
                    response_serializer=agent__service__pb2.StateResponse.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=agent__service__pb2.ActionRequest.FromString,
                    response_serializer=agent__service__pb2.ActionResponse.SerializeToString,
            ),
            'StepSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StepSimulation,
                    request_deserializer=agent__service__pb2.StepRequest.FromString,
                    response_serializer=agent__service__pb2.StepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecmsim.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecmsim.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecmsim.AgentService/GetState',
            agent__service__pb2.StateRequest.SerializeToString,
            agent__service__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecmsim.AgentService/ExecuteAction',
            agent__service__pb2.ActionRequest.SerializeToString,
            agent__service__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecmsim.AgentService/StepSimulation',
            agent__service__pb2.StepRequest.SerializeToString,
            agent__service__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
