# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_service.proto\x12\x06\x65\x63msim\"5\n\x0cStateRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tjammer_id\x18\x02 \x01(\x05\"S\n\rStateResponse\x12\r\n\x05state\x18\x01 \x03(\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x13\n\x0bjammer_mode\x18\x04 \x01(\t\"[\n\rActionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tjammer_id\x18\x02 \x01(\x05\x12\x11\n\tpower_dbm\x18\x03 \x01(\x01\x12\x10\n\x08jam_freq\x18\x04 \x01(\x01\"0\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"!\n\x0bStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\xbc\x02\n\x10RadarResultProto\x12\x10\n\x08radar_id\x18\x01 \x01(\x05\x12\x0f\n\x07sinr_db\x18\x02 \x01(\x01\x12\x16\n\x0e\x64\x65tect_success\x18\x03 \x01(\x08\x12\x19\n\x11jam_success_score\x18\x04 \x01(\x01\x12!\n\x19total_effective_jam_power\x18\x05 \x01(\x01\x12\x0e\n\x06jsr_db\x18\x06 \x01(\x01\x12\x1b\n\x13is_deception_active\x18\x07 \x01(\x08\x12\x1b\n\x13\x64\x65\x63\x65pt_effect_score\x18\x08 \x01(\x01\x12\x17\n\x0fjam_freq_deltas\x18\t \x03(\x01\x12\x1a\n\x12\x66req_match_factors\x18\n \x03(\x01\x12\x12\n\njammer_ids\x18\x0b \x03(\x05\x12\x1c\n\x14\x65\x66\x66\x65\x63tive_jam_powers\x18\x0c \x03(\x01\"\x83\x01\n\x0cStepResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.ecmsim.RadarResultProto\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x12\n\njammer_ids\x18\x04 \x03(\x05\x12\x14\n\x0cjammer_modes\x18\x05 \x03(\t2\xc4\x01\n\x0c\x41gentService\x12\x37\n\x08GetState\x12\x14.ecmsim.StateRequest\x1a\x15.ecmsim.StateResponse\x12>\n\rExecuteAction\x12\x15.ecmsim.ActionRequest\x1a\x16.ecmsim.ActionResponse\x12;\n\x0eStepSimulation\x12\x13.ecmsim.StepRequest\x1a\x14.ecmsim.StepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATEREQUEST']._serialized_start=31
  _globals['_STATEREQUEST']._serialized_end=84
  _globals['_STATERESPONSE']._serialized_start=86
  _globals['_STATERESPONSE']._serialized_end=169
  _globals['_ACTIONREQUEST']._serialized_start=171
  _globals['_ACTIONREQUEST']._serialized_end=262
  _globals['_ACTIONRESPONSE']._serialized_start=264
  _globals['_ACTIONRESPONSE']._serialized_end=312
  _globals['_STEPREQUEST']._serialized_start=314
  _globals['_STEPREQUEST']._serialized_end=347
  _globals['_RADARRESULTPROTO']._serialized_start=350
  _globals['_RADARRESULTPROTO']._serialized_end=666
  _globals['_STEPRESPONSE']._serialized_start=669
  _globals['_STEPRESPONSE']._serialized_end=800
  _globals['_AGENTSERVICE']._serialized_start=803
  _globals['_AGENTSERVICE']._serialized_end=999
# @@protoc_insertion_point(module_scope)
